name = "CloseOpenIntervals"
uuid = "fb6a15b2-703c-40df-9091-08a04967cfa9"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
